FROM python:alpine@sha256:452682e4648deafe431ad2f2391d726d7c52f0ff291be8bd4074b10379bb89ff



WORKDIR /var/www

RUN git config --global --add safe.directory /var/www \
    && addgroup -g 1000 appgroup \
    && adduser -D -u 1000 -G appgroup appuser \
    && chown -R appuser:appgroup /var/www

USER appuser

EXPOSE 9000